### ISSUE TITLE
setupTestFrameworkScriptFile Deprecation Warning

### ISSUE THREAD

**Issue by greyscaled** [bpedersen/jest-mock-console#12]
# Summary

Update `setupTestFrameworkScriptFile` to `setupFilesAfterEnv`

## Problem

When adding the following to `jest.config.js`

```js
{
  setupTestFrameworkScriptFile: 'jest-mock-console/dist/setupTestFramework.js',
}
```

Jest reports the following:

```
● Deprecation Warning:

  Option "setupTestFrameworkScriptFile" was replaced by configuration "setupFilesAfterEnv", which supports multiple paths.

  Please update your configuration.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```

## Context

```js
"devDependencies": {
    "@types/jest": "^24.0.22",
    "jest": "^24.9.0",
    "jest-mock-console": "^1.0.0",
    "ts-jest": "^24.1.0",
  }
```

## Potential Solution

The following seems to work:

```js
{
  setupFilesAfterEnv: [
    'jest-mock-console/dist/setupTestFramework.js',
  ],
}
```

## See Also

- [https://jestjs.io/docs/en/configuration#setupfilesafterenv-array](https://jestjs.io/docs/en/configuration#setupfilesafterenv-array)

**Comment by greyscaled** [comment]
I've opened a PR with what appears to be a working solution.

**Comment by bpedersen** [comment]
Looks good. Thanks for the PR
