### ISSUE TITLE
mockConsole() not returning function

### ISSUE THREAD

**Issue by robross0606** [bpedersen/jest-mock-console#14]
Calls to mockConsole() are not returning anything:
```Javascript
const mockConsole = require('jest-mock-console')

beforeEach(async () => {
  const consoleRestoreFn = mockConsole()
})
```
In this example, `consoleRestoreFn` ends up as `undefined`.

**Comment by bpedersen** [comment]
Sorry for the delay. I will make a fix for this, but for now you can do the following to get it to work.
`const mockConsole = require('jest-mock-console').default`
