### ISSUE TITLE
`jasmine is not defined` when used with `jest@27`

### ISSUE THREAD

**Issue by nolde** [bpedersen/jest-mock-console#18]
```
  ● Test suite failed to run
    ReferenceError: jasmine is not defined
      at Object.<anonymous> (node_modules/jest-mock-console/dist/setupTestFramework.js:9:24)
```

When using it with `jest@27.0.5`; problem goes away downgrading back to `jest@26.x`.

**Comment by bpedersen** [comment]
Thank you for bringing that to my attention. Apologies for the delay on responding. I will work on a fix for that now.

**Comment by bpedersen** [comment]
This issue for jest@27 appears to be that they have moved away from jasmine for the default test-runner https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults. 

This should only impact the Advanced use case of this library. The work around for now is to also include `"testRunner": "jest-jasmine2"` in your package.json.

I will leave this issue open for the time being while I look at a longer term resolution that will work with jest-circus

**Comment by jcollum** [comment]
I added that `jest-jasmine2` line and my coverage changed dramatically. An hour ago it was 89%, now it's dramatically lower. I can't figure out why. I'm just going to have to remove this tool and see if that's the issue.

**Comment by nolde** [comment]
Sorry to bother you @bpedersen , but did you ever release a version with this fix on it?

**Comment by bpedersen** [comment]
Just pushed version 1.2 which will now check for jest version and modify the describe block as needed.
