### ISSUE TITLE
How do you use this with jest.requireActual? 

### ISSUE THREAD

**Issue by jcollum** [bpedersen/jest-mock-console#22]
```
const mockConsole = jest.requireActual( "jest-mock-console"); 

describe('api calls', () => {

  beforeAll(() => {
    expect(jest.isMockFunction(mockConsole)).toBeFalsy();
```

Except that line is failing the test. 

I'm using `automock: true,` in my jest config, which is clearly part of the issue. But I should be able to use `requireActual` to get around that. But it doesn't appear to work. 

Also tried: 

```
const {mockConsole} = jest.requireActual( "jest-mock-console");
``` 

But then the test fails: 

```
TypeError: mockConsole is not a function 
 
> 11 | const restoreConsole = mockConsole();
```

Also tried

```
const mockConsole = jest.requireActual( "jest-mock-console");
```

But then the mock-check line `expect(jest.isMockFunction(mockConsole)).toBeFalsy();` fails.

**Comment by jcollum** [comment]
Next up I tried grabbing some code from the readme and turning automock off in the jest config: 

```
import mockConsole from "jest-mock-console";

describe('mock console', () => {
    it('works', () => {
        const restoreConsole = mockConsole(); // mockConsole returns a function to restore it back to normal
        console.error('This will not show in the test report');
        expect(console.error).toHaveBeenCalled();
        restoreConsole();
    });
});
```

That's the whole file. 

which fails: 

```
Matcher error: received value must be a mock or spy function

    Received has type:  function
    Received has value: [Function error]

      23 |     const restoreConsole = mockConsole(); // mockConsole returns a function to restore it back to normal
      24 |     console.error('This will not show in the test report');
    > 25 |     expect(console.error).toHaveBeenCalled();
```

    "jest": "27.1.0",
    "jest-mock-console": "1.1.0",

✗ node --version
v14.17.6

**Comment by jcollum** [comment]
I am using `jest-mock-console`  in another project with no issues -- but that project is using jest 27.0.6. Could that be the issue?

**Comment by jcollum** [comment]
Ignore this for now, I'm getting inconsistent failures.

**Comment by bpedersen** [comment]
I'm going to close this issue for now. Please let me know if you are still having issue with it.
