### ISSUE TITLE
[1.2.0] jest 26: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jlowcs** [bpedersen/jest-mock-console#26]
Since bumping to 1.2.0, all my tests are failing with the following:

![image](https://user-images.githubusercontent.com/3777724/135457629-b28b401f-dddb-48bf-bbb4-0f53f37b2e2d.png)

**Comment by bpedersen** [comment]
Can you tell me what version of jest you are running, and what cli options you are running jest with?

**Comment by jlowcs** [comment]
Hi! Sadly I'm still seeing the same issue with 1.2.1.

**Comment by jlowcs** [comment]
My config looks like this:

```js
const config = {
	rootDir: __dirname,
	testEnvironment: 'jsdom',
	maxWorkers: 2,
	setupFiles: [],
	setupFilesAfterEnv: [
		'<rootDir>/jest.setup.ts',
		'jest-plugin-unhandled-promise/setup',
		'@testing-library/jest-dom/extend-expect',
		'jest-mock-console/dist/setupTestFramework.js',
	],
	// necessary for compatibility with jest-mock-console
	testRunner: 'jest-jasmine2',
	coverageReporters: ['lcovonly', 'html', 'json-summary', 'json', 'text'],
	clearMocks: true,
	moduleFileExtensions: ['ts', 'tsx', 'json', 'js', 'jsx', 'node'],
	moduleDirectories: ['<rootDir>', 'node_modules'],
	moduleNameMapper: {
		/* ... */
	},
	transform: {
		'\\.(ts|js)x?$': 'babel-jest',
		'\\.(svg|png)$': '<rootDir>/__mocks__/imgTransform.js',
	},
	transformIgnorePatterns: [/* ... */],
	watchPathIgnorePatterns: ['/node_modules/'],
	testURL: 'http://localhost:3333/tests/',
	watchPlugins: ['jest-watch-master'],
	modulePathIgnorePatterns: [
		// ...
	],
}
```

**Comment by jlowcs** [comment]
And I'm getting the error simply by running `npx jest <filename>`

**Comment by jlowcs** [comment]
ok, found the fix. To support jest 26, I think you should be doing:

```js
if (majorVersion < 27) {
  var originalDescribe = jasmine.getEnv().describe;

  // ...
} else {
  var originalDescribe = describe;

  // ...
}
```

When making that change in node_modules, my tests go back to running with success.

**Comment by bpedersen** [comment]
That is the change in 1.2.1. Can you double check that 1.2.1 didn't fix the issue for you

**Comment by jlowcs** [comment]
The dist file wasn't updated: https://github.com/bpedersen/jest-mock-console/blob/master/dist/setupTestFramework.js

**Comment by bpedersen** [comment]
Thank you for that catch. I will modify my deployment script

**Comment by bpedersen** [comment]
Version 1.2.3 has been deployed with the correct dist. I'm going to mark this issue as closed
