### ISSUE TITLE
Confused with released versions and what changed in v2.0.0

### ISSUE THREAD

**Issue by stefcameron** [bpedersen/jest-mock-console#35]
Hello! Love this package. So useful. Thank you for maintaining it!

I'm confused by the 2.0.0 release that was just published to NPM 2 hours ago (which GitHub's Dependabot is alerting me to), yet this repository's package.json says the latest is 1.3.0.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/2855350/171455714-6e393aad-323d-4ca2-8e5e-dba7fd15cb00.png">

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/2855350/171456104-1d8730ef-3bb6-489c-96e9-60aa311fb60a.png">

Was that a mistake in the published version?

What changed that warranted a major? The latest commit ~19 hours ago just looks like bug fixes, not even new features, so why not just a 1.2.4 patch?

Just wanting to understand the versioning and the difference between the repo and NPM.

**Comment by bpedersen** [comment]
Sorry for the confusion. I was adding in support for jest-mock-console to allow it to function correctly when `--injectGlobals=false`. I was not sure of the potential of this to break certain setups and thus made a major version out of precaution. I unfortunately have not pushed the major version to the repo yet, I was going to do that now actually.

**Comment by stefcameron** [comment]
Ah, I see, makes sense. Thank you for explaining that discrepancy! 😄
