### ISSUE TITLE
Using it for logging instead of log suppressing

### ISSUE THREAD

**Issue by NoriSte** [bpedersen/jest-mock-console#5]
Hi
I was about to release almost the same package but when I realized it already exists I stopped myself. Just one consideration: I developed my package it with the opposite goal of your, I didn't need to hide the annoying logging but I'd like to have access to all the stuff logged.
Jest is infamous for logging because it updates the bash output and it's hard to analyze what the testing code is logging and what you're logging in your test files (and when a test fails it could be really useful). Using a mock you can at least do something like
`expect(console.log.mock.calls).toEqual([])` and immediately it outputs the full list of console log calls/params. I know that it's a workaround but it works.

So: could I update the readme and make a pull request explaining this particular use of your library? Or you prefer that I deploy on NPM a package dedicated to logging instead of hiding logging?

Thank you
Best
Stefano

**Comment by bpedersen** [comment]
Yeah, a PR is more than welcome. I think that is a great use case for the library

**Comment by NoriSte** [comment]
Ok thank you, expect a PR in the next days :)

**Comment by NoriSte** [comment]
Hi Pier
I'm very busy at work so... sorry if I haven't posted it yet. I don't forget to do it but probably I'll take more time than expected ;)
